---
####################
# Misc. enablement #
####################
configure_dotfiles: true

######################
# Dock Configuration #
######################
configure_dock: true
dockitems_remove: 
  - Launchpad
  - Beskeder
  - Mail
  - Kort
  - Fotos
  - FaceTime
  - Kontakter
  - Påmindelser
  - Noter
  - Freeform
  - TV
  - Musik
  - 'App Store'

dockitems_persist: 
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 2
  - name: "Brave Browser"
    path: "/Applications/Brave Browser.app/"
    pos: 3
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 4
  - name: "Alacritty"
    path: "/Applications/Alacritty.app/"
    pos: 5
  - name: "IntelliJ IDEA"
    path: "/Applications/IntelliJ IDEA.app/"
    pos: 6
  - name: "Webstorm"
    path: "/Applications/Webstorm.app/"
    pos: 7
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 8

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
