---
homebrew_installed_packages:
  - asdf
  - bat
  - btop
  - dockutil
  - eza
  - fzf
  - git
  - gh
  - glow
  - httpie
  - iperf
  - jq
  - lazydocker
  - lazygit
  - neovim
  - readline
  - openssl
  - stow
  - tmux
  - tmuxinator
  - tpm
  - wget
  - yazi

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - brave-browser
  - discord
  - docker
  - firefox
  - ghostty
  - google-chrome
  - google-drive
  - insomnia
  - intellij-idea
  - iterm2
  - jetbrains-toolbox
  - karabiner-elements
  - microsoft-office
  - plex
  - slack
  - skype
  - visual-studio-code
  - webstorm

homebrew_taps: []
