---
configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"x
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - nmap
  - pngpaste
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - brave-browser
  - discord
  - docker
  - firefox
  - google-chrome
  - google-drive
  - intellij-idea
  - jetbrains-toolbox
  - microsoft-office
  - slack
  - webstorm

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
