---
- name: Configure host.
  hosts: all

  vars_files:
    - vars/asdf.config.yml
    - vars/default.config.yml
    - vars/homebrew.config.yml
    - vars/nerdfont.config.yml
    - vars/packages.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: ctorgalson.nerdfonts
      when: install_nerdfonts
      tags: ['nerdfonts']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - name: Perform Homebrew post installation tasks
      import_tasks: tasks/homebrew-post-install.yml
      tags: ['homebrew']

    - import_tasks: tasks/install-zsh.yml
      tags: ['install-zsh']

    - import_tasks: tasks/stow.yml
      when: configure_dotfiles
      tags: ['stow']

    - name: Install ASDF Plugins      
      include_tasks: tasks/asdf-plugin-install.yml
      loop: "{{ asdf_plugins }}"
      loop_control:
        label: "Installing ASDF plugin {{ item.name }}"
      tags: ['asdf']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
