---
configure_dotfiles: true

######################
# Dock Configuration #
######################

configure_dock: true
dockitems_remove: 
  - Launchpad
  - Beskeder
  - Mail
  - Kort
  - Fotos
  - FaceTime
  - Kontakter
  - Påmindelser
  - Noter
  - Freeform
  - TV
  - Musik
  - 'App Store'

dockitems_persist: 
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 2
  - name: "Brave Browser"
    path: "/Applications/Brave Browser.app/"
    pos: 3
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 4

############
# Homebrew #
############

homebrew_installed_packages:
  - asdf
  - dockutil
  - fzf
  - git
  - gh
  - httpie
  - iperf
  - neovim
  - readline
  - openssl
  - tmux
  - tpm
  - wget

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - brave-browser
  - discord
  - docker
  - firefox
  - google-chrome
  - google-drive
  - intellij-idea
  - iterm2
  - jetbrains-toolbox
  - microsoft-office
  - slack
  - webstorm

##########################
# Package configurations #
##########################

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
