---
- name: Adding plugin
  shell: "asdf plugin add {{ item.name }} {{ item.plugin_url }}"

- name: Check if already installed
  shell: "asdf list {{ item.name}} | grep {{ item.lts_version }} || /usr/bin/false"
  register: installed
  ignore_errors: true

- name: Installing LTS version of toolchain managed by plugin
  shell:  "asdf install {{ item.name }} {{ item.lts_version }}"
  when: "installed.rc | int != 0"

- name: Reshim plugin
  shell: "asdf reshim {{ item.name }}"
  when: "installed.rc | int != 0"

- name: Remove old LTS version from global .tool-versions
  shell: "gsed -i '/{{ item.name }}/d' {{ lookup('env', 'HOME')/.tool-versions }}"
  when: "installed.rc | int != 0"

- name: Add new LTS version to global .tool-versions
  shell: "echo \"{{ item.name }} {{ item.lts_version }}\" >> {{ lookup('env', 'HOME') }}/.tool-versions"
  when: "installed.rc | int != 0"