---
- name: Determine installed version of Node.js
  set_fact:
    installed_node_version: "{{ asdf_plugins | selectattr('name','equalto', 'nodejs') | map(attribute='lts_version') }}"

- name: Install global NPM packages.
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: true
    executable: "{{ item.executable | default(omit) }}"
    environment:
      PATH: "{{ lookup('env', 'HOME') }}/.asdf/installs/nodejs/{{ installed_node_version }}/bin"
  loop: "{{ npm_packages }}"
