---
- name: Determine installed version of Node.js
  set_fact:
    installed_node_version: "{{ asdf_plugins | selectattr('name','equalto', 'nodejs') | map(attribute='lts_version') | first }}"

- name: Print the Node.js LTS version, used for installing Node.js packages
  debug:
    msg: |
      "The Node.js LTS version used, is: {{ installed_node_version }}"

- name: Install global NPM packages.
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.asdf/installs/nodejs/{{ installed_node_version }}/bin:{{ ansible_env.PATH }}"
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: true
  loop: "{{ npm_packages }}"

- name: Reshim binaries from installed NPM packages
  shell: "asdf reshim nodejs"